### PR TITLE
feat: made compatible with c++14

### PR DESCRIPTION
**Pull request by pranavpandey1998official**
#9

### CODE REVIEW

**Comment by mesozoic-drones** [comment]
Hello @pranavpandey1998official !

The main advantage of just_gtfs is that this library is header-only and has no dependencies. You propose to add boost for c++14 compatibility but it may be inconvenient in some use-cases and environments.

So I think there are two good options:

1) I create cpp14 branch and we merge your pull-request to this branch, not to the master (I think this is the best option).
2) You may create fork for c++14 support.

Thank you for your request!

**Comment by pranavpandey1998official** [comment]
yes I also think that making a separate branch is a good option

**Comment by mesozoic-drones** [comment]
> yes I also think that making a separate branch is a good option

I've created the new branch cpp14:
https://github.com/mapsme/just_gtfs/tree/cpp14

So you may change target branch of this PR to the cpp14 branch.

Also please fix the C++ CI build failure, so the build completes without failures on this new branch.

**Comment by mesozoic-drones** [comment]
@pranavpandey1998official Do you need help with CI? I can try to fix build failure.

**Comment by pranavpandey1998official** [comment]
@mesozoic-drones, that would be awesome, can you please try

**Comment by mesozoic-drones** [comment]
> @mesozoic-drones, that would be awesome, can you please try

Done. Thank you for your request!

**Pull request merged**
